#!/bin/bash
# mklive.sh — Build the MainDOB live filesystem blob.
#
# Produces a flat FAT32 superfloppy image (no MBR, no partition
# table, no GRUB) carrying the MainDOB userspace tree. The image is
# loaded into RAM by GRUB as a Multiboot module (cmdline "live_fs")
# and the kernel bootfs reads it from there — the CD never gets
# touched again after boot.
#
# Shares most of its body with mkbootdisk.sh on purpose: both build
# the same /SYSTEM and /DATA layout, only the disk-level wrapping
# differs (this one has none). Keep them in sync when adding new
# components to the tree.
#
# Usage: mklive.sh <live.img> <size_mb> <build_dir> <root_dir>

set -e

IMG="$1"
SIZE_MB="${2:-8}"
BUILD_DIR="$3"
ROOT_DIR="$4"

if [ -z "$IMG" ] || [ -z "$BUILD_DIR" ] || [ -z "$ROOT_DIR" ]; then
    echo "Usage: $0 <live.img> <size_mb> <build_dir> <root_dir>"
    exit 1
fi

cleanup() { rm -f /tmp/mlive_*_$$ 2>/dev/null; true; }
trap cleanup EXIT

echo "[LIVE] Creating ${SIZE_MB}MB live filesystem blob..."

# === 1. Create empty image and format as superfloppy FAT32 ===
# No partition table: mkfs.fat on the whole file produces a flat
# FAT32 volume starting at LBA 0. The kernel bootfs detects the
# absence of an MBR signature and treats it as superfloppy
# (part_lba = 0), so the same parser handles disk and ramdisk.
dd if=/dev/zero of="$IMG" bs=1M count="$SIZE_MB" 2>/dev/null
mkfs.fat -F 32 "$IMG" >/dev/null 2>&1
echo "[LIVE] FAT32 superfloppy formatted."

# === 2. mtools config — no partition, direct file access ===
ABSIMG="$(cd "$(dirname "$IMG")" && pwd)/$(basename "$IMG")"
export MTOOLSRC="/tmp/mlive_rc_$$"
cat > "$MTOOLSRC" << MEOF
mtools_skip_check=1
drive c:
    file="$ABSIMG"
MEOF

# === 3. Create directories ===
# No /boot/ on the live blob: GRUB lives on the ISO root, the kernel
# we boot is on the ISO too (loaded as the multiboot kernel, not
# read from inside this blob). The kernel.bin copy under
# /SYSTEM/OperatingSystem/ is kept — the installer reads it from
# here when laying down a fresh system.
echo "[LIVE] Creating directories..."
mmd c:/SYSTEM 2>/dev/null || true
mmd "c:/SYSTEM/OperatingSystem" 2>/dev/null || true
mmd c:/SYSTEM/PROGRAMS c:/SYSTEM/DRIVERS c:/SYSTEM/GAMES 2>/dev/null || true
mmd c:/SYSTEM/CONFIG 2>/dev/null || true
# Common files: the shared, sandbox-free area (/system/config/common_files).
# Anything dropped in the repo's common_files/fonts ships here and is picked up
# live by DobWrite's font scanner -- no rebuild of the program needed.
mmd "c:/SYSTEM/CONFIG/common_files" 2>/dev/null || true
mmd "c:/SYSTEM/CONFIG/common_files/fonts" 2>/dev/null || true
if [ -d "$ROOT_DIR/common_files/fonts" ]; then
    for ff in "$ROOT_DIR/common_files/fonts"/*; do
        [ -f "$ff" ] || continue
        mcopy "$ff" "c:/SYSTEM/CONFIG/common_files/fonts/$(basename "$ff")" \
            && echo "[LIVE] font: $(basename "$ff")"
    done
fi
mmd c:/DATA 2>/dev/null || true
mmd c:/DATA/Desktop c:/DATA/Documents c:/DATA/Downloads 2>/dev/null || true
mmd c:/DATA/Music c:/DATA/Video c:/DATA/Pictures c:/DATA/Screenshots 2>/dev/null || true

# === Audio test file ===
[ -f "$ROOT_DIR/boot/audioplayer/quack.mp2" ] && \
    mcopy "$ROOT_DIR/boot/audioplayer/quack.mp2" "c:/DATA/Music/quack.mp2"

# === 4. Kernel image (installer reads it from here) ===
echo "[LIVE] Copying kernel for installer..."
mcopy "$BUILD_DIR/kernel.bin" "c:/SYSTEM/OperatingSystem/kernel.bin"

# === 4b. GRUB blobs (installer writes them to target MBR + post-MBR) ===
# Generated by `make grub-blobs` (which the live target depends on).
# boot.img goes to target sector 0 (preserving partition table at 446-509);
# core.img to target sectors 1..ceil(size/512) (post-MBR gap).
if [ -f "$BUILD_DIR/grub-blobs/boot.img" ] && [ -f "$BUILD_DIR/grub-blobs/core.img" ]; then
    echo "[LIVE] Shipping GRUB blobs for installer..."
    mmd "c:/SYSTEM/OperatingSystem/grub-blobs" 2>/dev/null || true
    mcopy "$BUILD_DIR/grub-blobs/boot.img" "c:/SYSTEM/OperatingSystem/grub-blobs/boot.img"
    mcopy "$BUILD_DIR/grub-blobs/core.img" "c:/SYSTEM/OperatingSystem/grub-blobs/core.img"
else
    echo "[LIVE] WARNING: GRUB blobs missing — installer's INST_PHASE_GRUB will fail."
fi

# Helper
write_tmp() { echo "$1" > /tmp/mlive_tmp_$$; mcopy /tmp/mlive_tmp_$$ "$2"; }

# === 5. OS services ===
echo "[LIVE] Copying OS services..."
OS_SVCLIST="console config hotplug DobFileSystem inputd dobinterface settingsd"
OS_SRCDIRS="boot/console boot/config boot/hotplug boot/DobFileSystem boot/inputd boot/dobinterface boot/settingsd"
set -- $OS_SRCDIRS
for svc in $OS_SVCLIST; do
    srcdir="$1"; shift
    for d in boot programs drivers; do
        if [ -f "$BUILD_DIR/$d/${svc}.mdl" ]; then
            mmd "c:/SYSTEM/OperatingSystem/$svc" 2>/dev/null || true
            mcopy "$BUILD_DIR/$d/${svc}.mdl" "c:/SYSTEM/OperatingSystem/$svc/${svc}.mdl"
            [ -f "$ROOT_DIR/$srcdir/manifest.dob" ] && \
                mcopy "$ROOT_DIR/$srcdir/manifest.dob" "c:/SYSTEM/OperatingSystem/$svc/manifest.dob"
            write_tmp "0" "c:/SYSTEM/OperatingSystem/$svc/Visible"
            break
        fi
    done
done

# exfat.mem — exFAT parser companion for DobFileSystem, loaded at runtime
# via dob_mem_load. Not a service .mdl, so the loop above misses it.
# Without it EVERY exFAT mount fails ("cannot open exfat.mem"): desktop
# partition icons AND the boot-time definitive-volume attach. The
# installer copies the system from this live tree, so it must be here too.
if [ -f "$BUILD_DIR/boot/DobFileSystem/exfat.mem" ]; then
    mcopy "$BUILD_DIR/boot/DobFileSystem/exfat.mem" "c:/SYSTEM/OperatingSystem/DobFileSystem/exfat.mem"
    echo "[LIVE] exfat.mem copied"
else
    echo "[LIVE] note: exfat.mem not present (exFAT support not built)"
fi

# audioplayer and floppyprobe are drivers (audio service / CMOS floppy
# probe): they live under /SYSTEM/DRIVERS, not /SYSTEM/OperatingSystem,
# even though their sources sit in boot/. Visible=0 keeps them off the
# desktop; the module manager still lists them under "Driver".
for svc in audioplayer floppyprobe; do
    srcdir="boot/$svc"
    if [ -f "$BUILD_DIR/boot/${svc}.mdl" ]; then
        mmd "c:/SYSTEM/DRIVERS/$svc" 2>/dev/null || true
        mcopy "$BUILD_DIR/boot/${svc}.mdl" "c:/SYSTEM/DRIVERS/$svc/${svc}.mdl"
        [ -f "$ROOT_DIR/$srcdir/manifest.dob" ] && \
            mcopy "$ROOT_DIR/$srcdir/manifest.dob" "c:/SYSTEM/DRIVERS/$svc/manifest.dob"
        write_tmp "0" "c:/SYSTEM/DRIVERS/$svc/Visible"
    fi
done

# === 6. Drivers ===
echo "[LIVE] Copying drivers..."
for drv in rtc ata ahci usb_uhci usb_ehci usb_xhci usb_mass_storage ac97 maestro2e floppy cdrom bga mach64 x3100; do
    if [ -f "$BUILD_DIR/drivers/${drv}.mdl" ]; then
        mmd "c:/SYSTEM/DRIVERS/$drv" 2>/dev/null || true
        mcopy "$BUILD_DIR/drivers/${drv}.mdl" "c:/SYSTEM/DRIVERS/$drv/${drv}.mdl"
        [ -f "$ROOT_DIR/drivers/$drv/manifest.dob" ] && \
            mcopy "$ROOT_DIR/drivers/$drv/manifest.dob" "c:/SYSTEM/DRIVERS/$drv/manifest.dob"
        write_tmp "0" "c:/SYSTEM/DRIVERS/$drv/Visible"
    fi
done

# cdrom .mem companion (ISO9660 parser, loaded via dob_mem_load).
if [ -f "$BUILD_DIR/drivers/cdrom/iso9660.mem" ]; then
    mcopy "$BUILD_DIR/drivers/cdrom/iso9660.mem" "c:/SYSTEM/DRIVERS/cdrom/iso9660.mem"
fi

# === 7. Games ===
echo "[LIVE] Copying games..."
for game in snake tetris minesweeper uidemo solitaire spider arrowsweeper; do
    if [ -f "$BUILD_DIR/programs/${game}.mdl" ]; then
        mmd "c:/SYSTEM/GAMES/$game" 2>/dev/null || true
        mcopy "$BUILD_DIR/programs/${game}.mdl" "c:/SYSTEM/GAMES/$game/${game}.mdl"
        [ -f "$ROOT_DIR/programs/$game/manifest.dob" ] && \
            mcopy "$ROOT_DIR/programs/$game/manifest.dob" "c:/SYSTEM/GAMES/$game/manifest.dob"
        write_tmp "1" "c:/SYSTEM/GAMES/$game/Visible"
    fi
done

# === 8. Programs ===
echo "[LIVE] Copying programs..."
OS_SKIP="console config hotplug DobFileSystem inputd dobinterface snake tetris minesweeper uidemo solitaire spider arrowsweeper keymap settingsd"
for mdl in "$BUILD_DIR"/programs/*.mdl; do
    [ ! -f "$mdl" ] && continue
    name=$(basename "$mdl"); base="${name%.mdl}"; skip=false
    for s in $OS_SKIP; do [ "$base" = "$s" ] && skip=true; done
    if [ "$skip" = "false" ]; then
        mmd "c:/SYSTEM/PROGRAMS/$base" 2>/dev/null || true
        mcopy "$mdl" "c:/SYSTEM/PROGRAMS/$base/$name"
        [ -f "$ROOT_DIR/programs/$base/manifest.dob" ] && \
            mcopy "$ROOT_DIR/programs/$base/manifest.dob" "c:/SYSTEM/PROGRAMS/$base/manifest.dob"
        write_tmp "1" "c:/SYSTEM/PROGRAMS/$base/Visible"
        if [ "$base" = "DobPicture" ] && [ -f "$BUILD_DIR/programs/imgcodec.mem" ]; then
            mcopy "$BUILD_DIR/programs/imgcodec.mem" "c:/SYSTEM/PROGRAMS/DobPicture/imgcodec.mem"
        fi
    fi
done

# === 8b. keymap tray applet + layout files ===
if [ -f "$BUILD_DIR/programs/keymap.mdl" ]; then
    mmd "c:/SYSTEM/PROGRAMS/keymap" 2>/dev/null || true
    mcopy "$BUILD_DIR/programs/keymap.mdl" "c:/SYSTEM/PROGRAMS/keymap/keymap.mdl"
    [ -f "$ROOT_DIR/programs/keymap/manifest.dob" ] && \
        mcopy "$ROOT_DIR/programs/keymap/manifest.dob" "c:/SYSTEM/PROGRAMS/keymap/manifest.dob"
    for kbl in "$ROOT_DIR"/programs/keymap/*.kbl; do
        [ -f "$kbl" ] && mcopy "$kbl" "c:/SYSTEM/PROGRAMS/keymap/$(basename "$kbl")"
    done
    write_tmp "0" "c:/SYSTEM/PROGRAMS/keymap/Visible"
fi

# === 9. Startup_modules ===
# Same content as the installed-disk variant; the live kernel runs
# the very same boot sequence, only reading from RAM instead of ATA.
cat > /tmp/mlive_tmp_$$ << 'SMEOF'
# MainDOB Startup Modules — live boot
# Identical to the installed-system Startup_modules: the live
# kernel runs the same boot sequence, only the filesystem source
# differs (RAM vs ATA disk).

# /SYSTEM/OperatingSystem/console/console.mdl	driver
/SYSTEM/OperatingSystem/inputd/inputd.mdl	driver
# /SYSTEM/DRIVERS/rtc/rtc.mdl	driver
/SYSTEM/DRIVERS/ata/ata.mdl	driver
/SYSTEM/OperatingSystem/DobFileSystem/DobFileSystem.mdl
/SYSTEM/OperatingSystem/settingsd/settingsd.mdl	driver primary needs:DobFileSystem
/SYSTEM/OperatingSystem/config/config.mdl
/SYSTEM/OperatingSystem/hotplug/hotplug.mdl	driver
/SYSTEM/DRIVERS/floppyprobe/floppyprobe.mdl	driver needs:hotplug
/SYSTEM/OperatingSystem/dobinterface/dobinterface.mdl	driver primary needs:video
/SYSTEM/PROGRAMS/DobFiles/DobFiles.mdl	needs:dobinterface
/SYSTEM/PROGRAMS/keymap/keymap.mdl	needs:dobinterface
/SYSTEM/PROGRAMS/clock/clock.mdl	needs:dobinterface
/SYSTEM/DRIVERS/audioplayer/audioplayer.mdl	driver
# MainDOB_Setup auto-launches in live mode only: the live Startup_modules
# ships this line, the installed-disk Startup_modules (mkbootdisk.sh) does
# not. On an installed system the program is still present under
# /SYSTEM/PROGRAMS/ and can be re-launched manually from DobFiles, but
# it self-exits there (in_live_mode() returns false post-install).
#
# `driver` flag: required so the installer can (a) read .mdl files from
# /SYSTEM/OperatingSystem/ (sandbox_check denies non-driver read there)
# and (b) use spawn_file_driver -> make_driver to promote its spawned
# secondary DobFileSystem instance into a driver, which is what lets
# the secondary access the ATA disk to write the target partition.
/SYSTEM/PROGRAMS/MainDOB_Setup/MainDOB_Setup.mdl	driver needs:dobinterface
SMEOF
mcopy /tmp/mlive_tmp_$$ "c:/SYSTEM/CONFIG/Startup_modules"

# === 10. Live marker ===
# Presence of this file signals "live mode" to userspace. The
# installed-disk variant writes "installed" to /SYSTEM/CONFIG/installed
# instead; userspace components check for one or the other to know
# what kind of system they are running on.
write_tmp "live" "c:/SYSTEM/CONFIG/live"

# === 11. File type associations ===
cat > /tmp/mlive_tmp_$$ << 'ASSOCEOF'
.mdl=_spawn
.txt=/SYSTEM/PROGRAMS/editor/editor.mdl
.md=/SYSTEM/PROGRAMS/editor/editor.mdl
.cfg=/SYSTEM/PROGRAMS/editor/editor.mdl
.c=/SYSTEM/PROGRAMS/editor/editor.mdl
.h=/SYSTEM/PROGRAMS/editor/editor.mdl
.bmp=/SYSTEM/PROGRAMS/DobPicture/DobPicture.mdl
.png=/SYSTEM/PROGRAMS/DobPicture/DobPicture.mdl
.jpg=/SYSTEM/PROGRAMS/DobPicture/DobPicture.mdl
.wav=/SYSTEM/PROGRAMS/dobplayer/dobplayer.mdl
.mp2=/SYSTEM/PROGRAMS/dobplayer/dobplayer.mdl
.mp3=/SYSTEM/PROGRAMS/dobplayer/dobplayer.mdl
.tar=/SYSTEM/PROGRAMS/DobArchive/DobArchive.mdl
.zip=/SYSTEM/PROGRAMS/DobArchive/DobArchive.mdl
.dobw=/SYSTEM/PROGRAMS/DobWrite/DobWrite.mdl
.ttf=/SYSTEM/PROGRAMS/DobWrite/DobWrite.mdl
.otf=/SYSTEM/PROGRAMS/DobWrite/DobWrite.mdl
.dbp=/SYSTEM/PROGRAMS/DobInstaller/DobInstaller.mdl
ASSOCEOF
mcopy /tmp/mlive_tmp_$$ "c:/SYSTEM/CONFIG/Associations"

# === 12. DAS files ===
mmd "c:/SYSTEM/CONFIG/DAS" 2>/dev/null || true
for das in "$ROOT_DIR"/config/DAS/*.das; do
    [ -f "$das" ] && mcopy "$das" "c:/SYSTEM/CONFIG/DAS/$(basename "$das")"
done
# USB device-level DAS live in a subdirectory (read by the USB host-
# controller drivers, not by hotplug). The glob above only covers the top
# level, so copy the USB/ subdir explicitly.
mmd "c:/SYSTEM/CONFIG/DAS/USB" 2>/dev/null || true
for das in "$ROOT_DIR"/config/DAS/USB/*.das; do
    [ -f "$das" ] && mcopy "$das" "c:/SYSTEM/CONFIG/DAS/USB/$(basename "$das")"
done

rm -f "$MTOOLSRC"
SIZE_BYTES=$(stat -c%s "$IMG" 2>/dev/null || stat -f%z "$IMG")
echo "[LIVE] Live blob built: $IMG ($SIZE_BYTES bytes)"
